version: '3'

services:

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Passw0rd

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  web:
    build: .
    # command: python manage.py runserver 0.0.0.0:8000
    # ports:
    #   - "8000:8000"
    command: gunicorn web_app.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    volumes:
      - ./code:/app
      - staticfiles_volume:/app/static_collected
    depends_on:
      - db

  proxy:
    # image: nginx
    build: ./config/nginx
    volumes:
      - staticfiles_volume:/usr/share/nginx/html/static
    ports:
      - 5000:80
    depends_on:
      - web
    # command: rm -f /usr/share/nginx/html/*.html

volumes:
  staticfiles_volume:
    
