version: '3'

services:

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=web_app_dev_db
      - POSTGRES_USER=web_app_user
      - POSTGRES_PASSWORD=Passw0rd
    volumes:
      - postgres_data_volume:/var/lib/postgresql/data/

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  web:
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./code:/app
      - static_files_volume:/app/static_collected/
    depends_on:
      - db

  proxy:
    build: ./config/nginx
    volumes:
      - static_files_volume:/usr/share/nginx/html/static/
    ports:
      - 5000:80
    depends_on:
      - web

volumes:
  static_files_volume:
  postgres_data_volume:  
